FROM rust:1.61.0-bullseye AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin server

FROM gcr.io/distroless/cc
WORKDIR /app
COPY --from=builder /app/target/release/server ./

CMD ["/app/server"]
