FROM rust:1.61.0-bullseye AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin client

FROM gcr.io/distroless/cc
WORKDIR /app
COPY --from=builder /app/target/release/client ./

ENV AUTH_USER=peggy
ENV AUTH_PASS=secret

CMD ["/app/client"]
