services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/server
  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/client
    depends_on:
      - server
    environment:
      - AUTH_SERVER=server
      - AUTH_USER=peggy
      - AUTH_PASS=123123123
